# Generated by Django 3.0.8 on 2020-07-15 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='global_token',
            field=models.CharField(default=uuid.UUID('f7e94d72-5e62-4c1f-8580-b18a7336055e'), max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='join date'),
        ),
    ]
