# Generated by Django 3.0.8 on 2020-07-28 15:45

import account.models_addon
import account.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django_countries.fields
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200722_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, default="Hey there, I'm new here can you help with that.", max_length=200, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default=None, help_text='City/State Can have both, separated by a comma.', max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cover_pic',
            field=stdimage.models.StdImageField(default='static/default/img/cover.png', help_text='Limits:<ul><li>Size 4MB</li><li>Dimensions Range: Width & height (400-2600)</li></ul>', upload_to=account.models_addon.UploadToPathAndRename('upload/img/cover'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'PNG', 'JPG']), stdimage.validators.MinSizeValidator(400, 400), stdimage.validators.MaxSizeValidator(2600, 2600)], verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='Enter valid email: e.g. example@domain.com', max_length=60, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='facebook_url',
            field=models.URLField(blank=True, default=None, help_text='Link Should look like this: (https://)www.facebook.com/USERNAME/', null=True, validators=[account.validators.social_url_checker], verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='github_url',
            field=models.URLField(blank=True, default=None, help_text='Link Should look like this: (https://)www.github.com/USERNAME/', null=True, validators=[account.validators.social_url_checker], verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='linkedin_url',
            field=models.URLField(blank=True, default=None, help_text='Link Should look like this: (https://)www.linkedin.com/in/USERNAME/', null=True, validators=[account.validators.social_url_checker], verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=stdimage.models.StdImageField(default='static/default/img/profile.png', help_text='Limits:<ul><li>Size 2MB</li><li>Dimensions Range: Width & height (200-1600)</li></ul>', upload_to=account.models_addon.UploadToPathAndRename('upload/img/profile'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'PNG', 'JPG']), stdimage.validators.MinSizeValidator(200, 200), stdimage.validators.MaxSizeValidator(1600, 1600)], verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='account',
            name='twitter_url',
            field=models.URLField(blank=True, default=None, help_text='Link Should look like this: (https://)www.twitter.com/USERNAME/', null=True, validators=[account.validators.social_url_checker], verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. e.g. Mark99', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, default=None, help_text='Company Name can contain only a-zA-Z, digits and @/./+/-/_', max_length=150, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='middle_name',
            field=models.CharField(max_length=150, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True, verbose_name='Nationality'),
        ),
    ]
