# Generated by Django 3.0.8 on 2020-07-22 18:25

import account.models_addon
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for application at least 4 Char', max_length=255, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='title')),
                ('body', models.TextField(help_text='You can use HTML tags to style your body.', verbose_name='body')),
                ('job_title', models.CharField(max_length=255, verbose_name='job title')),
                ('place_name', models.CharField(default='Not specified yet', max_length=255, verbose_name='place name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True, verbose_name='longitude')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_pic', stdimage.models.StdImageField(default='static/default/img/application.png', upload_to=account.models_addon.UploadToPathAndRename('upload/img/application_cover'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'PNG', 'JPG']), stdimage.validators.MinSizeValidator(400, 400), stdimage.validators.MaxSizeValidator(2600, 2600)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_skill', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='english skill')),
                ('overall_skill', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='overall skill')),
                ('leading_skill', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='leading skill')),
                ('managing_skill', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='managing skill')),
                ('communication_skill', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='communication skill')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='question text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Apply')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='choice text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question')),
            ],
        ),
    ]
