# Generated by Django 3.0.8 on 2020-07-30 11:32

import account.models_addon
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationfile',
            name='real_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Real Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicationimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationimage',
            name='real_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Real Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applicationimage',
            name='image',
            field=stdimage.models.StdImageField(help_text='Make sure to add only supported extension: png, jpg and jpeg', max_length=255, upload_to=account.models_addon.UploadToPathAndRename('upload/img/application_cover'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), stdimage.validators.MinSizeValidator(400, 400), stdimage.validators.MaxSizeValidator(2600, 2600)], verbose_name='Application Cover'),
        ),
    ]
