# Generated by Django 3.0.8 on 2020-07-30 14:00

import account.models_addon
import django.core.validators
from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200730_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationimage',
            name='image',
            field=stdimage.models.StdImageField(default='static/default/img/application.png', help_text='Make sure to add only supported extension: png, jpg and jpeg', max_length=255, upload_to=account.models_addon.UploadToPathAndRename('upload/img/application_cover'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), stdimage.validators.MinSizeValidator(400, 400), stdimage.validators.MaxSizeValidator(2600, 2600)], verbose_name='Application Cover'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='communication_skill',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='Communication Skill'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='english_skill',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='English Skill'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='leading_skill',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='Leading Skill'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='managing_skill',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='Managing Skill'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='overall_skill',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Good'), (3, 'Medium'), (4, 'Low')], null=True, verbose_name='Overall Skill'),
        ),
    ]
